### ISSUE TITLE
getaddrinfo ENOTFOUND sui-mainnet-rpc.allthatnode.com

### ISSUE THREAD

**Issue by Im-Sue** [CetusProtocol/cetus-clmm-sui-sdk#13]
![image](https://github.com/user-attachments/assets/a5cd978e-4f75-4005-9ccb-20c30af69233)
![image](https://github.com/user-attachments/assets/2c6d6aeb-d9bf-4b73-8248-3de62d2e39ed)

I use the following in the development documentation: https://cetus-1.gitbook.io/cetus-developer-docs#latest -The latest configuration in SDK config：
cause: Error: getaddrinfo ENOTFOUND sui-mainnet-rpc.allthatnode.com
at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
errno: -3008,
code: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'sui-mainnet-rpc.allthatnode.com'
}
﻿

**Comment by Im-Sue** [comment]
![image](https://github.com/user-attachments/assets/9875c350-e4d4-4fd9-b11c-6cd16f45e615)

**Comment by Nebula-Spark** [comment]
Use diffrent rpc url
