### ISSUE TITLE
utils/common.ts/buildPosition Validation Error

### ISSUE THREAD

**Issue by icegriffinguru** [CetusProtocol/cetus-clmm-sui-sdk#8]
https://github.com/CetusProtocol/cetus-clmm-sui-sdk/blob/3ff730264688ece50a6e31b499fa2d80ef9aab7c/src/utils/common.ts#L201

When I queried my Position, objects.error was not empty while object.data.content was correct.
The error was `'Could not find the referenced transaction events 
 TransactionEventsDigest(EoX7bG16cqGe6T6n7DbvJMpau9j6psCaoNDF4XQu3NqN)].'`
 I doubt why we need `objects.error != null` validation in `buildPosition` function.

**Comment by devlb1024** [comment]
Thanks for the feedback. Fixed in v5.1.2
